// SPDX-License-Identifier: GPL-2.0
#ifndef FONT_CN_H
#define FONT_CN_H
/**
 * \file
 *
 * 16x16 CJK bitmap font covering the subset of characters used by the
 * Chinese user interface. Generated by tools/gen_cn_font.ps1.
 *//*
 * Copyright (C) 2024.
 */

#include <stdint.h>

/**
 * Number of glyphs in cn_font_data.
 */
extern const int          cn_font_count;

/**
 * Sorted list of the Unicode code points covered by cn_font_data.
 * cn_font_data[i] is the glyph for cn_font_codepoints[i].
 */
extern const uint32_t     cn_font_codepoints[];

/**
 * 16x16 glyphs, one bit per pixel, most significant bit first.
 */
extern const uint16_t     cn_font_data[][16];

/**
 * Returns the index into cn_font_data of the glyph for the given code
 * point, or -1 if the code point is not covered by this font.
 */
int cn_font_lookup(uint32_t codepoint);

#endif // FONT_CN_H
