#!/usr/bin/env python3
# gen_cn_font.py
#
# Linux counterpart of tools/gen_cn_font.ps1. Behaviour is identical to the
# PowerShell script: it scans the whole source tree for CJK / full-width
# characters, renders EVERY code point as a 16x16 1-bit glyph (no
# anti-aliasing, ink bounding box centred in the cell) and fully regenerates
# system/font_cn.c.
#
# Usage (from the repository root):
#   python3 tools/gen_cn_font.py /path/to/font.ttf|ttc|otf [size-in-px]
#
# Requirements: python3 with Pillow. On Windows prefer the original
# gen_cn_font.ps1 (GDI+ SingleBitPerPixelGridFit + YaHei).

import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
FONT_C = REPO / "system" / "font_cn.c"

SCAN_DIRS = ["app", "tests", "lib"]

COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.S)


def collect_codepoints():
    """Step 1: strip comments, collect CJK code points from the sources."""
    cps = set()
    for d in SCAN_DIRS:
        for f in (REPO / d).rglob("*"):
            if f.suffix not in (".c", ".h"):
                continue
            text = COMMENT_RE.sub(" ", f.read_text(encoding="utf-8"))
            for ch in text:  # Python iterates full code points (no surrogates)
                cp = ord(ch)
                if 0x2E80 <= cp <= 0x2FFFF and cp != 0xFFFD:
                    cps.add(cp)
                elif cp == 0x2103:  # '℃'
                    cps.add(cp)
    if not cps:
        sys.exit("No CJK characters found in the scanned sources.")
    return cps


def render_glyph(font, cp):
    """Step 2: render one code point as 16 rows of uint16 (MSB = leftmost)."""
    img = Image.new("L", (32, 32), 0)
    draw = ImageDraw.Draw(img)
    draw.text((8, 8), chr(cp), font=font, fill=255)
    px = img.load()

    min_x, max_x, min_y, max_y = 99, -1, 99, -1
    for y in range(32):
        for x in range(32):
            if px[x, y] > 127:
                min_x, max_x = min(min_x, x), max(max_x, x)
                min_y, max_y = min(min_y, y), max(max_y, y)

    rows = [0] * 16
    if max_x < 0:
        return rows, False  # empty glyph
    dx = (16 - (max_x - min_x + 1)) // 2 - min_x
    dy = (16 - (max_y - min_y + 1)) // 2 - min_y
    dx = max(-min_x, min(dx, 15 - max_x))
    dy = max(-min_y, min(dy, 15 - max_y))
    for y in range(32):
        ty = y + dy
        if not 0 <= ty <= 15:
            continue
        for x in range(32):
            tx = x + dx
            if 0 <= tx <= 15 and px[x, y] > 127:
                rows[ty] |= 0x8000 >> tx
    return rows, True


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_cn_font.py <font-file> [size-in-px]")
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 16
    font = ImageFont.truetype(sys.argv[1], size, index=0)

    codepoints = sorted(collect_codepoints())

    rows_by_cp = {}
    empty = []
    for cp in codepoints:
        rows, ok = render_glyph(font, cp)
        if not ok:
            empty.append(chr(cp))
        rows_by_cp[cp] = rows

    # Step 3: emit system/font_cn.c.
    n = len(codepoints)
    cp_list = ", ".join(f"0x{cp:04X}" for cp in codepoints)

    lines = []
    lines.append("// SPDX-License-Identifier: GPL-2.0")
    lines.append("//")
    lines.append("// 16x16 CJK bitmap font. GENERATED by tools/gen_cn_font.py -- DO NOT EDIT.")
    lines.append(f"// Source font: {Path(sys.argv[1]).name} {size}px (1-bit threshold, grid-fitted).")
    lines.append(f"// Covers the {n} CJK / full-width characters used by the UI string literals.")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append('#include "font_cn.h"')
    lines.append("")
    lines.append(f"const int cn_font_count = {n};")
    lines.append("")
    lines.append(f"const uint32_t cn_font_codepoints[{n}] = {{ {cp_list} }};")
    lines.append("")
    lines.append(f"const uint16_t cn_font_data[{n}][16] = {{")
    for cp in codepoints:
        rows = ", ".join(f"0x{v:04X}" for v in rows_by_cp[cp])
        lines.append(f"    /* {chr(cp)} */ {{ {rows} }},")
    lines.append("};")
    lines.append("")
    lines.append("int cn_font_lookup(uint32_t codepoint)")
    lines.append("{")
    lines.append("    int lo = 0;")
    lines.append("    int hi = cn_font_count - 1;")
    lines.append("    while (lo <= hi) {")
    lines.append("        int mid = lo + (hi - lo) / 2;")
    lines.append("        if (cn_font_codepoints[mid] == codepoint) return mid;")
    lines.append("        if (cn_font_codepoints[mid] <  codepoint) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else {")
    lines.append("            hi = mid - 1;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return -1;")
    lines.append("}")
    FONT_C.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {FONT_C} ({n} glyphs)")
    if empty:
        print(f"WARNING: glyphs rendered empty (font lacks them?): {''.join(empty)}")


if __name__ == "__main__":
    main()
